version: "3.8"
services:
  doggies-db:
    image: mysql:latest
    ports:
      - "32000:3306"
    volumes:
      - ./init-db.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

  script:
    build: .
    image: doggie-bot:latest
    volumes:
      - ./main.py:/doggie-bot/main.py
    depends_on:
      - doggies-db
    env_file:
      - ./secrets.env
