CREATE DATABASE IF NOT EXISTS doggies;
USE doggies;
CREATE TABLE IF NOT EXISTS links (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dog_id VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    title TEXT,
    notified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;
